### ISSUE TITLE
Python 3.7 SSL module not available

### ISSUE THREAD

**Issue by AndyPandy77** [StarbotDiscord/BuildScript#10]
I have Python 3.7.1 installed on Windows 7 from www.python.org. When I want to "pip install pylab" I receive the following message: "pip is configured with locations that require tls/ssl however the ssl module in python is not available". Please help me to overcome this problem. Many thanks

**Comment by dhinakg** [comment]
There's an open issue about this at #9, could you confirm that it's related?

**Comment by 1byte2bytes** [comment]
>I have Python 3.7.1 installed on Windows 7 from www.python.org.

You're commenting on an issue for someone who installed Python from a place **other than** this script. This issue has nothing to do with this script.
